### ISSUE TITLE
5.5. 列族 拼写错误

### ISSUE THREAD

**Issue by cpplm** [ablozhou/hbasedoc_cn#1]
5.5. 列族
column 前缀必须是可打印的字符，剩下的部分(称为qualify),可以又任意字节数组组成。

问题1，英文逗号的问题，这个是不是可以全局替换一下？
问题2，“可以又任意字节数组组成”中的“又”字是否是拼写错误？改为“可以由任意字节数组组成”比较好一些？

**Comment by ablozhou** [comment]
标点暂没改。

错别字已改正。
